/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.itechbear.robotstxt4j;

public interface RobotsParseHandler {
    void HandleRobotsStart();

    void HandleRobotsEnd();

    void HandleUserAgent(int line_num, String value);

    void HandleAllow(int line_num, String value);

    void HandleDisallow(int line_num, String value);

    void HandleSitemap(int line_num, String value);

    // Any other unrecognized name/value pairs.
    void HandleUnknownAction(int line_num, String action, String value);
}
